// angular-app/src/app/components/favourites/favourites.component.ts
import { Component, OnInit } from '@angular/core';
import { Movie } from '../models.model';

@Component({
  selector: 'app-favourites',
  templateUrl: './favourites.component.html',
  styleUrls: ['./favourites.component.css']
})
export class FavouritesComponent implements OnInit {
  favouritesList = new Array<Movie>();

  constructor() { }

  ngOnInit() {
    const localStorageKeys = Object.keys(localStorage);

    localStorageKeys.forEach(key => {
      const movie = localStorage.getItem(key);

      if(movie != null){
        this.favouritesList.push(JSON.parse(movie))
      }
    })
  }

  removeFromFavourite(movieId: number, movieIndex: number) {
    this.favouritesList.splice(movieIndex, 1);
    localStorage.removeItem(movieId.toString());
  }
}

<div class="container">
  <div class="row mt-2">
    <div class="col-3 mb-3" *ngFor="let movie of favouritesList; let movieIndex = index;">
      <div class="movie-card">
        <img [src]="movie.Cover">
        <button type="button" class="btn btn-danger btn-sm btn-block favourite-btn" (click)="removeFromFavourite(movie.Id, movieIndex)">Remove from favourites</button>

        <div class="movie-details">
          <div class="movie-genre" *ngFor="let genre of movie.Genres">{{genre}}</div>
        </div>

      </div>
    </div>

  </div>
</div>

// react-app/src/Components/Favourites/Favourites.js
import './../Home/Home.css'
import { useEffect, useState } from 'react';

const Favourites = () => {
  const [favouriteList, setfavouriteList] = useState([])

  useEffect(() => {
    const localStorageKeys = Object.keys(localStorage);
    let favouritesArr = [];

    localStorageKeys.forEach(key => {
      const movie = JSON.parse(localStorage.getItem(key));

      if(movie != null && movie.Id != null){
        favouritesArr.push(movie)
      }
    })

    setfavouriteList(favouritesArr);
  }, [])

  const removeFromFavourite = (movieId, movieIndex) => {
    let favourites = [...favouriteList];
    favourites.splice(movieIndex, 1);

    setfavouriteList(favourites);

    localStorage.removeItem(movieId.toString());
  }

  return (
    <div className="container">
      <div className="row mt-2">
        {favouriteList.map((movie, i) => (
          <div className="col-3 mb-3" key={`favourite-movie-${i}`}>
            <div className="movie-card">
              <img src={movie.Cover} alt=""/>
              <button type="button" className="btn btn-danger btn-sm btn-block favourite-btn" onClick={() => removeFromFavourite(movie.Id, i)}>Remove from favourites</button>

              <div className="movie-details">
                {movie.Genres.map((genre, genreId) => (
                  <div className="movie-genre" key={`movie-${i}-genre-${genreId}`}>{genre}</div>
                ))}                
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}


export default Favourites;
